In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.3.3


In [3]:
a=[1,2,3,4,5]
print(type(a))

<class 'list'>


In [4]:
b=np.array(a)
print(type(b))

<class 'numpy.ndarray'>


In [5]:
print(a)
print(b)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [6]:
c = np.array([1,2,3,4])
print(c)
print(type(c))


[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
arr= np.arange(4)
print(arr)
print(type(arr))


[0 1 2 3]
<class 'numpy.ndarray'>


In [9]:
print(np.ones(3,dtype=int))

[1 1 1]


In [12]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
np.linspace(0,5,2)

array([0., 5.])

In [23]:
np.linspace(start = 0,stop = 5,num = 3,endpoint = False, dtype=int)

array([0, 1, 3])

In [24]:
np.full(shape=(2,2),fill_value=5,dtype=int)

array([[5, 5],
       [5, 5]])

In [26]:
np.random.random(5)

array([0.48809297, 0.76189638, 0.32265347, 0.83430829, 0.84249416])

In [30]:
np.random.randint(low=40,high=50,size=(3,2),dtype=int)

array([[48, 48],
       [42, 46],
       [44, 49]], dtype=int32)

In [31]:
np.eye(3,3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
#two dimensional array
[[]]
a =np.array([[2,1,4,3,],[6,5,7,8]])
print(a)
print(type(a))

[[2 1 4 3]
 [6 5 7 8]]
<class 'numpy.ndarray'>
