In [1]:
import numpy as np

In [5]:
#create a 2by3
arr=np.array([[3,3,5],[5,7,8]])
print(array.ndim)
print(arr)

2
[[3 3 5]
 [5 7 8]]


In [6]:
print(arr.size)
print(arr.shape)

6
(2, 3)


In [7]:
arr2=arr.reshape(3,2)
print(f"arr2:{arr2}")
arr3=arr.reshape(6,1)
print(f"arr3:{arr3}")

arr2:[[3 3]
 [5 5]
 [7 8]]
arr3:[[3]
 [3]
 [5]
 [5]
 [7]
 [8]]


In [10]:
#concatination, join two or more arrays
a = np.array([5,6,8])
b = np.array([3,9,1])

In [11]:
np.concatenate((a,b),axis=0)

array([5, 6, 8, 3, 9, 1])

In [13]:
c= np.array([[5,6,8]])
d = np.array([[3,9,1]])

In [12]:
np.concatenate((a,b),axis=None)

array([5, 6, 8, 3, 9, 1])

In [14]:
np.concatenate((c,d),axis=1)

array([[5, 6, 8, 3, 9, 1]])

In [15]:
np.concatenate((c,d),axis=0)

array([[5, 6, 8],
       [3, 9, 1]])

In [ ]:
#Broadcasting
np.array([[10,20,30],[10,40,50],[60,70,80]])