In [2]:
import numpy as np

In [3]:
a=np.array([[34,9,12],[36,14,10],[15,16,24]])
print(a)

[[34  9 12]
 [36 14 10]
 [15 16 24]]


In [11]:
np.sort(a,axis=None)[::-1]

array([36, 34, 24, 16, 15, 14, 12, 10,  9])

In [5]:
np.sort(a,axis=0)

array([[15,  9, 10],
       [34, 14, 12],
       [36, 16, 24]])

In [7]:
np.sort(a,axis=-1)

array([[ 9, 12, 34],
       [10, 14, 36],
       [15, 16, 24]])

In [2]:
#argsort
y=np.array([4,5,1,7,9])


NameError: name 'np' is not defined

In [ ]:
np.argsort(ny)

array([2, 0, 1, 3, 4])

In [19]:
#k smallest vallue in array
num=np.array([5,1,3,9,7,4,8,20,19,14,30,78,18])


In [21]:
np.partition(num,2)

array([ 1,  3,  4,  5,  7,  8,  9, 14, 18, 19, 20, 30, 78])

In [31]:
arr4=np.array([1,3,5,8,7,9,4,6])

In [33]:
np.sort(arr4)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [36]:
index 3 ; 5
index 5 ; 7

np.partition(arr4,(3,5))

SyntaxError: invalid syntax (2951082309.py, line 1)

In [39]:
rand=np.random.RandomState(42)
x=rand.randint(0,10,(4,6))
x

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [40]:
np.partition(x,3,axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]], dtype=int32)

In [46]:
#Basic math operations
r=np.random.random(5)
w=np.random.random(5)


In [47]:
np.add(r,w)

array([0.67032487, 1.35234126, 1.01882228, 0.23363079, 0.99911372])

In [51]:
arr=np.array([[1,2,6,7],[6,7,8,9],[11,22,55,13]])
arr

array([[ 1,  2,  6,  7],
       [ 6,  7,  8,  9],
       [11, 22, 55, 13]])

In [54]:
arr[2,2]

np.int64(55)

In [55]:
arr[1,0:-1:2]

array([6, 8])