# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [5]:
arr=np.array([[4,5,6],[7,3,6],[2,9,1]])
np.pad(arr,pad_width=1,mode='constant',constant_values=0)

array([[0, 0, 0, 0, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 3, 6, 0],
       [0, 2, 9, 1, 0],
       [0, 0, 0, 0, 0]])

17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [7]:
x=[1,2,3,4]
np.diag(x,k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [9]:
b= np.ones((8,8),dtype=int)
b[1::2, ::2]=0
b[::2, 1::2]=0

print(b)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [27]:
g= np.arange(336).reshape(6,7,8)

indx= np.unravel_index(99, g.shape,)

print(indx)
print("Value at that index:", g[indx])


(np.int64(1), np.int64(5), np.int64(3))
Value at that index: 99


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [32]:
b= np.array([[0,1,],[0,1]])

np.tile(b, (4, 4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [37]:
v= np.random.rand(5,5)
norm_v = (v - v.min()) / (v.max() - v.min())

print("Original matrix:\n", v)
print("\nNormalized matrix:\n", norm_v)


Original matrix:
 [[0.56472363 0.01846808 0.20893507 0.46511708 0.02212223]
 [0.58340142 0.43170743 0.87658833 0.87028077 0.04230765]
 [0.58507358 0.18581553 0.22561205 0.19648884 0.79006819]
 [0.28918033 0.38729377 0.50487354 0.90506638 0.14291204]
 [0.29081812 0.46786934 0.71318829 0.2960592  0.1763993 ]]

Normalized matrix:
 [[0.61612519 0.         0.21482895 0.50377831 0.00412154]
 [0.637192   0.46609536 0.96787942 0.96076508 0.0268888 ]
 [0.63907804 0.18875228 0.23363904 0.20079078 0.87029279]
 [0.30533812 0.4160009  0.54861989 1.         0.14036115]
 [0.30718538 0.50688261 0.78357945 0.31309683 0.17813165]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [40]:
m=np.array([[9,2,1],[4,3,2],[7,8,4],[6,5,1],[2,3,1]])
h=np.array([[7,1],[6,1],[5,4]])

c=np.dot(m,h)
print(c)

[[ 80  15]
 [ 56  15]
 [117  31]
 [ 77  15]
 [ 37   9]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [61]:
arr = np.arange(10)
arr
arr[3:8] *= -1

print(arr)


[ 0  1  2 -3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z**z
2 << z >> 2
1j*z
z/1/1
Z<Z>Z

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
result=nan
np.array(0) // np.array(0)
result= error
np.array([np.nan]).astype(int).astype(float)


#### 29. How to round away from zero a float array ? (★☆☆)

In [68]:
arr=np.array([-0.2,4.5,-3.1,2.5,1.7])

r = np.where(arr > 0, np.ceil(arr), np.floor(arr))

print(r)


[-1.  5. -4.  3.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [69]:
w=np.array([11,12,13,14,15])
z=np.array([20,11,14,16,10])

same=np.intersect1d(w,z)
print(same)

[11 14]
