# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

2.3.3


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
np.zeros((10), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array (★☆☆)

In [48]:
arr = np.array(5)
print("itemsize:", arr.itemsize, "bytes")

itemsize: 8 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [47]:

np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\dorice asami\desktop\pydata\dorice\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
a = np.zeros((10), dtype=int)
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [16]:
arr=np.arange(10,50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [20]:
arr=np.arange(10,50)

b= arr[::-1]
print(b)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [28]:
np.arange(9).reshape(3, 3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [45]:
y=np.array([1,2,0,0,4,0])

y[y != 0]

array([1, 2, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [41]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [35]:
np.random.randint(low=30,high=70,size=(3,3,3),dtype=int )

array([[[35, 69, 59],
        [32, 41, 67],
        [41, 69, 48]],

       [[32, 64, 33],
        [44, 61, 57],
        [36, 57, 66]],

       [[40, 37, 58],
        [32, 33, 69],
        [64, 63, 32]]], dtype=int32)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [30]:
np.random.randint(low=30,high=70,size=(10,10),dtype=int )

array([[33, 36, 54, 59, 68, 63, 38, 59, 36, 60],
       [53, 47, 52, 44, 49, 46, 54, 54, 41, 65],
       [45, 68, 43, 66, 50, 34, 42, 45, 62, 65],
       [40, 48, 59, 34, 58, 65, 33, 59, 38, 36],
       [39, 61, 57, 31, 46, 63, 49, 35, 48, 58],
       [44, 62, 30, 50, 61, 59, 45, 33, 63, 55],
       [59, 67, 68, 64, 57, 43, 63, 47, 33, 43],
       [55, 53, 38, 51, 61, 45, 40, 63, 48, 33],
       [57, 31, 48, 36, 53, 44, 56, 64, 54, 65],
       [52, 35, 49, 30, 64, 65, 66, 63, 30, 32]], dtype=int32)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
temp=np.random.randint(low=16,high=40,size=(30))
print (temp)
np.mean(temp)


[33 24 18 20 27 33 35 31 31 37 36 19 38 37 25 23 31 16 30 17 26 27 16 37
 27 24 28 19 24 33]


np.float64(27.4)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [49]:
np.array([[1,0]])


array([[1, 0]])