# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1)
output; nan

np.emath.sqrt(-1)
1j

np.sqrt(-1) == np.emath.sqrt(-1); False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [10]:
today= np.datetime64('today','D')

yesterday= today- np.timedelta64(1, 'D')

tomorrow = today + np.timedelta64(1, 'D')

print("yesterday:", yesterday)
print("today:", today)
print("tomorrow :", tomorrow)

yesterday: 2025-09-13
today: 2025-09-14
tomorrow : 2025-09-15


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [12]:
start=np.datetime64('2016-07')
end=np.datetime64('2016-08')

dates=np.arange(start,end,dtype= 'datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [40]:
a=np.array([5.0,6.5,7.2])
b=np.array([2.1,4.0,8.1])

np.add(a,b, out=a)

ans=np.multiply(a, -0.5)

np.multiply(a,ans, out=a)

print(a)

[ -25.205  -55.125 -117.045]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
arr=np.linspace(0,10,5)
print('original array:', arr)

#using astype int
arr1=arr.astype(int)
print(arr1)


original array: [ 0.   2.5  5.   7.5 10. ]
[ 0  2  5  7 10]


In [ ]:
#using .floor method
arr=np.linspace(0,10,5)
arr2=np.floor(arr)
arr2

array([ 0.,  2.,  5.,  7., 10.])

In [38]:
#using .fix method
arr=np.linspace(0,10,5)
arr3=np.fix(arr)
arr3

array([ 0.,  2.,  5.,  7., 10.])

In [ ]:
#using .trunc method
arr=np.linspace(0,10,5)
arr4 = np.trunc(arr)
arr4

array([ 0.,  2.,  5.,  7., 10.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [16]:
m=np.arange(0,4)
a = np.tile(m,(5,1))

print(a)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [44]:
num = (x+1 for x in range(10))
np.fromiter(num, int)




array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [48]:
v=np.linspace(0,1,12)[1:-1]

print(v)



[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [50]:
arr=np.arange(10)

np.argsort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)